stages:
  - prepare
  - deploy

Prepare Node Modules:
  stage: prepare
  image: node:10-alpine
  script:
    - node -v
    - npm -v
    - npm install
    - cat src/variables/constants/config.js
  cache:
    key: billard-control-${CI_PIPELINE_ID}
    paths:
      - node_modules/
      - package-lock.json
      - .npmrc
    policy: push

PROD:
  stage: deploy
  image: node:10-alpine
  dependencies:
    - Prepare Node Modules
  environment:
    name: PROD
    url: https://billard-control.web.app
  variables:
    FIREBASE_APIKEY: ${FIREBASE_APIKEY_DEV}
  before_script:
    - node -v
    - npm -v
    - npm install -g firebase-tools firebase-ci
    - npm run build
  script:
    - firebase-ci createConfig --project "dev" --path "src/variables/constants/config.js"
    - firebase use --token $FIREBASE_DEPLOY_KEY billard-control
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
  cache:
    key: billard-control-${CI_PIPELINE_ID}
    paths:
      - node_modules/
      - package-lock.json
      - .npmrc
    policy: pull
  only:
    - master

DEV:
  stage: deploy
  image: node:10-alpine
  dependencies:
    - Prepare Node Modules
  environment:
    name: DEV
    url: https://billard-control-dev.web.app
  variables:
    FIREBASE_APIKEY: ${FIREBASE_APIKEY_PROD}
  before_script:
    - node -v
    - npm -v
    - npm install -g firebase-tools firebase-ci
    - npm run build
  script:
    - firebase-ci createConfig --project "prod" --path "src/variables/constants/config.js"
    - firebase use --token $FIREBASE_DEPLOY_KEY billard-control-dev
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
  cache:
    key: billard-control-${CI_PIPELINE_ID}
    paths:
      - node_modules/
      - package-lock.json
      - .npmrc
    policy: pull
  only:
    - develop
